# Generated by Django 3.2.8 on 2021-11-06 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='password2',
        ),
    ]
