# Generated by Django 2.2.13 on 2022-01-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.TextField(null=True)),
                ('productName', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('sellingPrice', models.IntegerField()),
                ('discountPrice', models.IntegerField()),
                ('image1', models.ImageField(upload_to='post_images')),
                ('image2', models.ImageField(upload_to='post_images')),
                ('image3', models.ImageField(upload_to='post_images')),
                ('image4', models.ImageField(upload_to='post_images')),
            ],
        ),
    ]
