# Generated by Django 2.2.13 on 2022-01-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='discountPrice',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='sellingPrice',
            field=models.IntegerField(null=True),
        ),
    ]
